version: '3'
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    container_name: $COMPOSE_PROJECT_NAME-postgres
    ports:
      - 0.0.0.0:$POSTGRES_EXTERNAL_PORT:$POSTGRES_INTERNAL_PORT
    environment:
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  node:
    container_name: $COMPOSE_PROJECT_NAME-node
    image: node:${NODE_VERSION}-alpine
    restart: no
    ports:
      - 0.0.0.0:$NODE_EXTERNAL_PORT:$NODE_INTERNAL_PORT
    volumes:
      - ../.env:/.env
      - ../dist:/dist
      - ../public:/public
      - ../package.json:/package.json
      - ../node_modules:/node_modules
      - ../views:/views
    command: npm run start